runtime: custom
env: flex
service: eve-valuation-engine

entrypoint: streamlit run app.py --server.port=8080 --server.address=0.0.0.0 --server.headless=true

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

